"use client";

import { useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, Bot, Check, CheckCircle2, ChevronDown, CircleUserRound, Clock3, Database, FileSearch, Gauge, Headphones, ImageIcon, LayoutDashboard, Mail, MessageSquareText, Network, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Star, TicketCheck, Upload, Users, Wrench, X, Zap } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";

type PageKey = "dashboard" | "knowledge" | "assistant" | "service" | "orders" | "quality";
const nav = [
  ["dashboard", "运营总览", LayoutDashboard], ["knowledge", "企业知识中枢", Database], ["assistant", "智能问答", Sparkles],
  ["service", "智能客服", Headphones], ["orders", "检修工单", Wrench], ["quality", "智能质检", ShieldCheck],
] as const;
const trend = [{d:"09/18",s:2380,r:1610},{d:"09/19",s:2720,r:1870},{d:"09/20",s:2490,r:1710},{d:"09/21",s:3080,r:2180},{d:"09/22",s:2840,r:2010},{d:"09/23",s:3190,r:2260},{d:"今日",s:3286,r:2347}];
const channels = [{name:"网页客服",value:36,color:"#1677ff"},{name:"微信服务号",value:28,color:"#10b981"},{name:"企业微信",value:21,color:"#7c3aed"},{name:"语音转写",value:15,color:"#f59e0b"}];
const faults = [{name:"互联网专线",value:168},{name:"企业宽带",value:126},{name:"云主机",value:84},{name:"5G专网",value:51},{name:"安全服务",value:32}];
const docs = [
  ["互联网专线产品手册 V3.2","产品手册","政企客户部","V3.2","2026-09-23","已发布","1,286"],
  ["政企客户故障申告处理规范","制度流程","客户服务部","V2.6","2026-09-22","已发布","985"],
  ["重大网络故障应急预案","应急预案","网络维护中心","V4.1","2026-09-20","已发布","746"],
  ["5G定制网售前技术问答","FAQ","解决方案部","V1.9","2026-09-18","审核中","538"],
  ["制造园区云网融合解决方案","解决方案","工业行业部","V2.1","2026-09-16","已发布","412"],
];

function Title({eyebrow,title,desc,children}:{eyebrow:string;title:string;desc:string;children?:React.ReactNode}){return <div className="page-title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{desc}</p></div><div className="title-actions">{children}</div></div>}
function Panel({title,sub,children,className,action}:{title:string;sub?:string;children:React.ReactNode;className?:string;action?:React.ReactNode}){return <section className={cn("panel",className)}><header><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{action}</header><div className="panel-body">{children}</div></section>}
function Metric({label,value,delta,icon:Icon,tone="blue"}:{label:string;value:string;delta:string;icon:React.ElementType;tone?:string}){return <div className="metric"><span className={`metric-icon ${tone}`}><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong><em>{delta} 较昨日</em></div></div>}

function Dashboard({go}:{go:(p:PageKey)=>void}){return <><Title eyebrow="智慧运营中心" title="早上好，运营管理员" desc="今日整体服务运行平稳，3 个高优先级工单需要关注。"><Button onClick={()=>go("service")}><Headphones size={16}/>进入客服工作台</Button></Title><div className="metrics"><Metric label="今日接待量" value="3,286" delta="+12.6%" icon={MessageSquareText}/><Metric label="机器人解决率" value="71.4%" delta="+3.2%" icon={Bot} tone="green"/><Metric label="工单按时办结" value="96.7%" delta="+1.4%" icon={TicketCheck} tone="violet"/><Metric label="客户满意度" value="94.2%" delta="+2.1%" icon={Star} tone="orange"/></div><div className="dashboard-grid"><Panel title="服务量趋势" sub="近 7 日服务总量与机器人独立解决量" className="span2"><div className="chart"><ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1677ff" stopOpacity={.25}/><stop offset="1" stopColor="#1677ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e8eef5" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="s" name="服务总量" stroke="#1677ff" strokeWidth={2.5} fill="url(#fill)"/><Area dataKey="r" name="机器人解决" stroke="#10b981" strokeWidth={2} fill="none"/></AreaChart></ResponsiveContainer></div></Panel><Panel title="渠道分布" sub="今日客户接入渠道"><div className="pie"><div><ResponsiveContainer><PieChart><Pie data={channels} dataKey="value" innerRadius={44} outerRadius={66} paddingAngle={4} strokeWidth={0}>{channels.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>3,286</b><small>总会话</small></span></div><ul>{channels.map(c=><li key={c.name}><i style={{background:c.color}}/>{c.name}<b>{c.value}%</b></li>)}</ul></div></Panel><Panel title="产品故障分布" sub="近 24 小时关联故障量" className="span2"><div className="chart short"><ResponsiveContainer><BarChart data={faults} layout="vertical"><CartesianGrid stroke="#eef2f7" horizontal={false}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={84}/><Tooltip/><Bar dataKey="value" fill="#3b82f6" radius={[0,5,5,0]} barSize={12}/></BarChart></ResponsiveContainer></div></Panel><Panel title="重点预警" sub="需要立即关注的服务风险"><div className="alerts"><button onClick={()=>go("orders")}><AlertTriangle/><span><b>P1 专线故障即将超时</b><small>新区智造科技 · 剩余 42 分钟</small></span><ArrowRight/></button><button onClick={()=>go("service")}><MessageSquareText/><span><b>重复投诉情绪升级</b><small>负向情绪 91%</small></span><ArrowRight/></button><button onClick={()=>go("knowledge")}><BookOpen/><span><b>37 条候选知识待审核</b><small>8 条来自今日人工工单</small></span><ArrowRight/></button></div></Panel></div></>}

function Knowledge(){const[q,setQ]=useState("");return <><Title eyebrow="企业知识中枢" title="统一知识，精准服务" desc="汇聚云网产品、网络运维、客户服务与工业场景知识，实现可追溯的智能检索。"><Button variant="outline"><Upload size={16}/>批量导入</Button><Button><Plus size={16}/>新建知识</Button></Title><div className="metrics"><Metric label="知识文档" value="12,684" delta="+436" icon={BookOpen}/><Metric label="有效知识片段" value="186,520" delta="+2.8%" icon={Database} tone="violet"/><Metric label="问答命中率" value="91.8%" delta="+1.9%" icon={Gauge} tone="green"/><Metric label="待审核知识" value="37" delta="8 条新增" icon={Clock3} tone="orange"/></div><div className="knowledge-grid"><Panel title="知识空间" sub="8 个业务主题空间"><div className="spaces">{[["云网产品知识库","3,286 份",Network],["网络运维与检修","2,418 份",Wrench],["客户服务规范","1,976 份",Headphones],["园区行业解决方案","1,528 份",Zap],["工业知识库","1,206 份",Settings],["供应商管理知识库","864 份",Users]].map(([n,c,I],i)=><button className={i===0?"active":""} key={String(n)}><i><I size={17}/></i><span><b>{String(n)}</b><small>{String(c)}</small></span><ArrowRight size={14}/></button>)}</div></Panel><Panel title="知识文档" sub="云网产品知识库 · 最近更新" className="doc-panel" action={<label className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索文档"/></label>}><div className="doc-table"><div className="doc-row head"><span>文档名称</span><span>分类</span><span>来源部门</span><span>版本</span><span>更新时间</span><span>状态</span><span>调用量</span></div>{docs.filter(d=>d[0].includes(q)||d[1].includes(q)).map(d=><div className="doc-row" key={d[0]}><span className="doc-name"><i>PDF</i><b>{d[0]}</b></span>{d.slice(1,5).map((v,i)=><span key={i}>{v}</span>)}<span><Badge variant="outline" className={d[5]==="已发布"?"live":"review"}>{d[5]}</Badge></span><span>{d[6]}</span></div>)}</div></Panel></div></>}

function Assistant({create}:{create:()=>void}){const[asked,setAsked]=useState(false);const[loading,setLoading]=useState(false);const[input,setInput]=useState("新区工厂的互联网专线从上午9点开始频繁丢包，生产系统登录很慢");const ask=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setAsked(true)},900)};return <><Title eyebrow="多模态智能问答" title="云网知识助手" desc="上传告警截图或输入问题，系统将检索企业知识并给出可追溯答案。"><Badge variant="outline" className="online"><i/>知识服务正常</Badge></Title><div className="chat-shell"><aside className="history"><Button><Plus size={16}/>新建会话</Button><small>今天</small><button className="active"><MessageSquareText/><span><b>互联网专线频繁丢包</b><small>刚刚</small></span></button><button><MessageSquareText/><span><b>云主机如何在线扩容</b><small>10:24</small></span></button><small>昨天</small><button><MessageSquareText/><span><b>5G专网交付材料清单</b><small>昨天</small></span></button></aside><main className="chat-main"><div className="chat-scroll"><div className="welcome"><i><Sparkles/></i><div><h2>您好，我是云网知识助手</h2><p>我可以回答产品、运维、服务规范与工业场景问题，并提供知识来源。</p></div></div><div className="prompts"><button onClick={()=>setInput("专线出现丢包率升高，应按什么顺序排查？")}>专线故障排查</button><button onClick={()=>setInput("5G专网项目从商机到交付需要哪些材料？")}>5G专网交付</button><button onClick={()=>setInput("云主机能否从4核8G在线扩容到8核16G？")}>云主机扩容</button></div>{asked&&<><div className="user-msg"><div><b>新区智造科技有限公司</b><p>{input}</p><small><ImageIcon/>专线告警截图.png</small></div><CircleUserRound/></div><div className="bot-msg"><i><Bot/></i><div><div className="answer-meta"><Badge><Check/>置信度 86%</Badge><span>已检索 3 份有效知识</span></div><p>根据告警截图与客户电路信息，系统识别到 <b>LOS 告警</b>，当前接收光功率为 <b>-25.8 dBm</b>，近 30 分钟丢包率为 <b>18.6%</b>。初步判断为园区汇聚链路光衰异常。</p><ol><li>核验同区域关联告警与影响范围；</li><li>检查 OLT 端口及光功率，复测主干光路；</li><li>排查客户侧路由器和交换设备；</li><li>本客户为金牌客户，建议立即生成 P1 检修工单。</li></ol><div className="citations"><button><FileSearch/><span><b>[1] 政企客户故障申告处理规范</b><small>V2.6 · 第 18 页</small></span></button><button><FileSearch/><span><b>[2] 企业专线常见故障案例汇编</b><small>V3.1 · 第 42 页</small></span></button></div><div className="answer-actions"><Button size="sm" onClick={create}><TicketCheck/>创建 P1 检修工单</Button><Button size="sm" variant="outline">转人工复核</Button></div></div></div></>}</div><div className="composer"><div><ImageIcon/><span>已附加：专线告警截图.png</span><X/></div><section><button><Plus/></button><textarea value={input} onChange={e=>setInput(e.target.value)}/><Button onClick={ask}>{loading?<Activity className="spin"/>:<Send/>}{loading?"诊断中":"发送"}</Button></section><small>答案由企业知识库生成，重要业务请以人工确认为准</small></div></main><aside className="evidence"><h3>检索与诊断</h3>{[["问题理解","专线故障 · 丢包 · 高优先级"],["图片识别","LOS告警 · XZ-OLT-03"],["知识检索","召回 12 条 · 重排 3 条"],["网络诊断",asked?"丢包率 18.6% · 光功率异常":"等待执行"]].map((s,i)=><div className="trace" key={s[0]}><i>{i<3?<Check/>:4}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></div>)}<div className="confidence"><span>综合置信度</span><b>{asked?"86%":"—"}</b><Progress value={asked?86:0}/><small>阈值：78% · 高风险规则已触发</small></div></aside></div></>}

function Service({create}:{create:()=>void}){const[sent,setSent]=useState(false);return <><Title eyebrow="智能客服运营中心" title="全渠道客服工作台" desc="统一接待、智能辅助、快速诊断和检修派单。"><Badge className="queue">当前排队 8</Badge><Button variant="outline"><BarChart3/>坐席看板</Button></Title><div className="service-shell"><aside className="conv-list"><header><h3>会话队列</h3><Search/></header><nav><button className="active">待处理 8</button><button>处理中 3</button></nav>{[["新区智造科技有限公司","专线故障 · 金牌客户","刚刚"],["华星商贸有限公司","宽带续费 · 普通客户","2分钟前"],["新区政务服务中心","云主机扩容 · 重要客户","5分钟前"],["恒科电子制造","5G专网咨询 · 战略客户","8分钟前"]].map((c,i)=><button className={i===0?"conv active":"conv"} key={c[0]}><i>{c[0].slice(0,2)}</i><span><b>{c[0]}</b><small>{c[1]}</small></span><em>{c[2]}</em></button>)}</aside><main className="service-chat"><header><div><i>新区</i><span><b>新区智造科技有限公司</b><small>● 网页客服 · 会话中</small></span></div><Button size="sm">结束会话</Button></header><div className="messages"><small>今天 10:32</small><div className="customer"><i>新区</i><p>我们工厂的互联网专线从上午9点开始一直丢包，生产系统登录很慢。</p></div><div className="customer"><i>新区</i><p className="alarm"><AlertTriangle/>专线告警截图.png</p></div><div className="agent"><p>您好，已为您识别电路信息并进行远程诊断。系统检测到园区汇聚链路光功率异常，我正在为您升级检修处理。<small>10:34 · AI 辅助生成</small></p><i>客</i></div>{sent&&<div className="agent"><p>已为您创建 P1 检修工单 <b>XZ202609240087</b>，网络维护中心将在 30 分钟内响应。<small>刚刚 · 已送达</small></p><i>客</i></div>}</div><footer><textarea defaultValue="已为您创建 P1 检修工单 XZ202609240087，网络维护中心将在 30 分钟内响应。"/><Button size="sm" onClick={()=>setSent(true)}><Send/>发送</Button></footer></main><aside className="copilot"><header><span><Sparkles/>AI 坐席助手</span><Badge variant="outline">实时</Badge></header><div className="customer-card"><p><span>客户等级</span><b className="gold">金牌客户</b></p><p><span>产品实例</span><b>互联网专线</b></p><p><span>电路编号</span><b>XZ-IP-…0176</b></p><p><span>SLA</span><b>30分钟/4小时</b></p></div><div className="risk"><AlertTriangle/><span><b>高风险 · 需优先处理</b><small>负向情绪 78%，生产业务受影响</small></span></div><h4>AI 诊断建议</h4><div className="diagnosis"><p><span>接入设备</span><b>XZ-OLT-03</b></p><p><span>端口状态</span><b className="ok">在线</b></p><p><span>接收光功率</span><b className="bad">-25.8 dBm</b></p><p><span>近30分钟丢包</span><b className="bad">18.6%</b></p><div>初判：园区汇聚链路光衰异常，建议派发网络维护中心复测。</div></div><Button className="full" onClick={create}><TicketCheck/>生成检修工单</Button><h4>推荐知识</h4><button className="recommend"><FileSearch/><span><b>专线故障申告处理规范</b><small>相关度 96% · V2.6</small></span><ArrowRight/></button></aside></div></>}

function Orders({stage,setStage}:{stage:number;setStage:(n:number)=>void}){const stages=["工单创建","智能派发","专员受理","检修处理","客户确认","完成归档"];return <><Title eyebrow="检修工单中心" title="工单 XZ202609240087" desc="互联网专线丢包 · 新区智造科技有限公司"><Badge className="p1">P1 紧急</Badge><Button variant="outline">更多操作<ChevronDown/></Button></Title><div className="steps">{stages.map((s,i)=><div className={cn(i<=stage&&"active",i<stage&&"done")} key={s}><i>{i<stage?<Check/>:i+1}</i><b>{s}</b>{i<5&&<span/>}</div>)}</div><div className="order-grid"><main><Panel title="故障与诊断信息" sub="已关联客户、产品实例与综合网管模拟数据"><div className="details">{[["客户名称","新区智造科技有限公司"],["产品实例","互联网专线"],["电路编号","XZ-IP-20260918-0176"],["故障发生","2026-09-24 09:00"],["影响范围","生产系统约 160 个终端"],["责任部门","新区网络维护中心"]].map(d=><p key={d[0]}><span>{d[0]}</span><b>{d[1]}</b></p>)}</div><div className="diag-strip">{[["接入设备","XZ-OLT-03"],["端口状态","在线"],["光功率","-25.8 dBm"],["丢包率","18.6%"],["关联告警","3 条"]].map((d,i)=><p key={d[0]}><span>{d[0]}</span><b className={i===1?"ok":i===2||i===3?"bad":""}>{d[1]}</b></p>)}</div><div className="ai-result"><Sparkles/><span><b>AI 初步判断</b><p>园区汇聚链路光衰异常，建议网络维护中心复测主干光路并检查熔接点。置信度 86%。</p></span></div></Panel><Panel title="处理时间轴" sub="Trace ID：TRC-20260924-8F72A9"><div className="timeline">{[["客户提交故障","上传专线告警截图。"],["AI 完成多模态诊断","识别 LOS 告警，调用模拟网管。"],["生成 P1 检修工单","自动派发网络维护中心。"]].map(x=><div className="done" key={x[0]}><i><Check/></i><span><b>{x[0]}</b><p>{x[1]}</p><small>系统自动</small></span></div>)}{stage>=2&&<div className="done"><i><Mail/></i><span><b>检修专员已接收通知</b><p>邮件 MAIL-6F28A 投递成功，王工已受理。</p><small>10:36 · 邮件工作流</small></span></div>}{stage>=3&&<div className="done"><i><Wrench/></i><span><b>现场检修完成</b><p>重新熔接尾纤，光功率恢复至 -18.2 dBm。</p><small>11:18 · 王工</small></span></div>}<div className="current"><i>{stage+1}</i><span><b>{stages[stage]}</b><p>流程处理中，页面状态将实时同步。</p><small>当前节点</small></span></div></div></Panel></main><aside><Panel title="SLA 服务保障"><div className="sla"><div><b>{stage>=4?"已恢复":"02:38"}</b><small>{stage>=4?"提前完成":"剩余解决时间"}</small></div></div><p className="sla-row"><span>响应时限</span><b className="ok">✓ 4 分钟</b></p><p className="sla-row"><span>解决时限</span><b>4 小时</b></p></Panel><Panel title="负责人"><div className="owner"><i>王</i><span><b>王海峰</b><small>网络维护中心 · 检修专员</small></span><Mail/></div></Panel><Panel title="流程操作"><Button className="full" onClick={()=>setStage(Math.min(stage+1,5))} disabled={stage===5}>{["智能派发","模拟专员受理","回写检修结果","提交客户确认","确认并归档","工单已完成"][stage]}<ArrowRight/></Button></Panel></aside></div></>}

function Quality(){return <><Title eyebrow="智能质检中心" title="全量会话质量洞察" desc="自动识别服务风险、定位证据语句，并形成坐席整改闭环。"><Button><ShieldCheck/>新建质检任务</Button></Title><div className="metrics"><Metric label="本月质检会话" value="28,640" delta="+18.2%" icon={MessageSquareText}/><Metric label="平均质检得分" value="92.7" delta="+1.6" icon={Gauge} tone="green"/><Metric label="高风险会话" value="46" delta="-8.4%" icon={AlertTriangle} tone="orange"/><Metric label="服务规范率" value="96.3%" delta="+2.1%" icon={ShieldCheck} tone="violet"/></div><div className="quality-grid"><Panel title="质检规则表现" sub="本周各项服务规范达标率" className="span2"><div className="rules">{[["身份核验",98],["标准问候与结束语",96],["诉求识别完整性",94],["工单号告知",91],["情绪安抚",88],["无不当服务承诺",97]].map(([n,v])=><p key={String(n)}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><em>{v}%</em></p>)}</div></Panel><Panel title="风险会话" sub="AI 自动识别的重点问题"><div className="risks">{[["高","未经确认承诺恢复时间","坐席 A017 · 10:28"],["中","重复投诉未执行升级","坐席 A032 · 09:46"],["中","结束前未确认是否解决","坐席 A008 · 09:31"]].map(r=><p key={r[1]}><i className={r[0]==="高"?"high":"mid"}>{r[0]}</i><span><b>{r[1]}</b><small>{r[2]}</small></span></p>)}</div></Panel></div></>}

export default function Home(){const[page,setPage]=useState<PageKey>("dashboard");const[collapsed,setCollapsed]=useState(false);const[stage,setStage]=useState(1);const[toast,setToast]=useState("");const go=(p:PageKey)=>{setPage(p);window.scrollTo({top:0})};const create=()=>{setStage(1);setToast("P1 检修工单 XZ202609240087 已创建并完成智能派发");setTimeout(()=>setToast(""),3000);setTimeout(()=>go("orders"),400)};return <div className={cn("app",collapsed&&"collapsed")}><aside className="sidebar"><div className="brand"><i><span/></i>{!collapsed&&<div><b>中国电信</b><small>CHINA TELECOM</small></div>}</div><div className="demo">{collapsed?"演示":"演示环境 · 模拟数据"}</div><nav>{nav.map(([k,l,I])=><button key={k} className={page===k?"active":""} onClick={()=>go(k)}><I/>{!collapsed&&<span>{l}</span>}</button>)}</nav><footer><button><Bell/>{!collapsed&&<span>消息中心</span>}</button><button><Settings/>{!collapsed&&<span>系统设置</span>}</button><button onClick={()=>setCollapsed(!collapsed)}><ArrowRight/>{!collapsed&&<span>收起导航</span>}</button></footer></aside><section className="main"><header className="topbar"><div><span>新区分公司</span><i>/</i><b>{nav.find(n=>n[0]===page)?.[1]}</b></div><label><Search/><input placeholder="搜索知识、客户或工单…"/><kbd>⌘ K</kbd></label><aside><span className="status">● 服务正常</span><button><i>运</i><span><b>运营管理员</b><small>新区分公司</small></span><ChevronDown/></button></aside></header><main className="content">{page==="dashboard"&&<Dashboard go={go}/>} {page==="knowledge"&&<Knowledge/>}{page==="assistant"&&<Assistant create={create}/>} {page==="service"&&<Service create={create}/>} {page==="orders"&&<Orders stage={stage} setStage={setStage}/>} {page==="quality"&&<Quality/>}</main></section>{toast&&<div className="toast"><CheckCircle2/><span>{toast}</span><button onClick={()=>setToast("")}><X/></button></div>}</div>}
